apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-serving
resources:
- namespace.yaml
- gateway.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- service-role.yaml
- service-role-binding.yaml
- role-binding.yaml
- config-map.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
- apiservice.yaml
- image.yaml
- hpa.yaml
commonLabels:
  kustomize.component: knative
images:
- newTag: 88d864eb3c47881cf7ac058479d1c735cc3cf4f07a11aad0621cd36dcd9ae3c6
  name: gcr.io/knative-releases/knative.dev/serving/cmd/activator@sha256
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/activator@sha256
- newTag: a7801c3cf4edecfa51b7bd2068f97941f6714f7922cb4806245377c2b336b723
  name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa@sha256
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler-hpa@sha256
- newTag: aeaacec4feedee309293ac21da13e71a05a2ad84b1d5fcc01ffecfa6cfbb2870
  name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler@sha256
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler@sha256
- newTag: 3b096e55fa907cff53d37dadc5d20c29cea9bb18ed9e921a588fee17beb937df
  name: gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/controller@sha256
- newTag: 057c999bccfe32e9889616b571dc8d389c742ff66f0b5516bad651f05459b7bc
  name: gcr.io/knative-releases/knative.dev/serving/cmd/networking/istio@sha256
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/networking/istio@sha256
- newTag: e0654305370cf3bbbd0f56f97789c92cf5215f752b70902eba5d5fc0e88c5aca
  name: gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256
- newTag: c2076674618933df53e90cf9ddd17f5ddbad513b8c95e955e45e37be7ca9e0e8
  name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook@sha256
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/webhook@sha256
